
all:
	javac ProblemOne.java
	javac ProblemTwo.java
	javac ProblemThree.java

run1:
	java ProblemOne 1
	
run2:
	java ProblemOne 2

run3:
	java ProblemOne 3

run4:
	java ProblemTwo 4

run5a:
	java ProblemTwo 5a

run5b:
	java ProblemTwo 5b

run6:
	java ProblemThree 6

run7a:
	java ProblemThree 7a

run7b:
	java ProblemThree 7b

clean:
	rm -rf *.class


