
all:
	javac TestProblemOne.java
	javac TestProblemTwo.java
	javac TestProblemThree.java
	javac TestCaseGenerator.java

cases:
	java TestCaseGenerator


test1:
	java TestProblemOne

test2:
	java TestProblemTwo
	
test3:
	java TestProblemThree



clean:
	rm -rf *.class

remove_case:
	rm -rf *.txt


